@api=http://localhost:3000


GET {{api}}/impuesto/listar
###
POST {{api}}/impuesto/crear
Content-Type: application/json

{
  "nombre": "IGV",
  "tasa": 18,
  "tipo_impuesto": "Incluido_en_el_precio"
}
###
GET {{api}}/impuesto/listar/16
###
PUT {{api}}/impuesto/actualizar/16
Content-Type: application/json

{
  "nombre": "nombre",
  "tasa": 50,
  "tipo_impuesto": "Incluido_en_el_preckk"
}
###
DELETE {{api}}/impuesto/eliminar/51
