@api=http://localhost:3000/empleado
POST  {{api}}
Content-Type: application/json

{
  "nombre": "Angelo Lopez",
  "email":"angelo@gmail.com",
  "telefono": "987456321",
  "password":"12345",
  "cargo": "Cajero",
  "pais":"Perú",
  "propietarioId": 1
}
###
PUT  {{api}}/4
Content-Type: application/json

{
  "nombre": "Angelo Lopez",
  "email":"angelo1@gmail.com",
  "telefono": "987456321",
  "password":"12345",
  "cargo": "Cajero",
  "pais":"Perú"
}