@api=http://localhost:3000


GET {{api}}/categoria/listar
###
POST {{api}}/categoria/crear
Content-Type: application/json

{
  "nombre": "Almohadas",
  "color":"Celeste"
}
###
GET {{api}}/categoria/listar/botellas_de_plstico
###
PUT {{api}}/categoria/actualizar/laptop_acer
Content-Type: application/json

{
  "nombre": "Laptop Toshiba",
  "color":"Azul"
}
###
DELETE {{api}}/categoria/eliminar/Caramelos