
@api=http://localhost:3000

POST {{api}}/registro
Content-Type: application/json

{
  "nombre": "Estefany",
  "email": "jo@gmail.com",
  "password": "12346785",
  "pais": "Perú"
}
###
POST {{api}}/login
Content-Type: application/json

{

  "email": "estefanyt3101@gmail.com",
  "password": "holamellamoestefany"
}