@api=http://localhost:3000
###
GET {{api}}/venta
Content-Type: application/json

{
  "detalles": [
    {
      "cantidad": 1,
      "articuloId": 3
    }
  ],
  "tipoPago": "Efectivo",
  "dineroRecibido":500
}
###
GET {{api}}/reembolso/recibo/56
###
POST {{api}}/reembolsar
Content-Type: application/json

{
  "id":11, 
  "detalles": [
    {
      "cantidad": 1,
      "articuloId": 1
    },
    {
      "cantidad": 1,
      "articuloId": 5
    }
  ]
}