@api=http://localhost:3000
###
POST {{api}}/venta
Content-Type: application/json

{
  "detalles": [
    {
      "cantidad": 1,
      "articuloId": 1
    },
    {
        "cantidad": 4,
        "articuloId": 2
    }
  ],
  "tipoPago": "Efectivo",
  "impuestoId": 1,
  "descuentoId": 2,
  "clienteId":1,
  "usuarioId":1,
  "dineroRecibido":500
}
###
GET {{api}}/recibo
###
POST {{api}}/reembolsar
Content-Type: application/json

{
  "id": 3, 
  "detalles": [
    {
      "cantidad": 2,
      "articuloId": 2
    }
  ]
}