@api=http://localhost:3000/cliente
GET {{api}}
###

###
POST {{api}}
Content-Type: application/json

{
  "nombre": "Mario gomez",
  "email": "mariogomez@gmail.com",
  "telefono": "921448207",
  "direccion": "Calle Las Pasionarias",
  "ciudad": "Lima",
  "region": "Lima",
  "codigo_postal":"15313",
  "pais": "Perú"
  
}

###
GET {{api}}/1
###
PUT {{api}}/1
Content-Type: application/json

{
  "nombre": "Luis",
  "email": "lucho456@gmail.com",
  "telefono": "921448207",
  "direccion": "Calle Las Pasionarias",
  "ciudad": "Lima",
  "region": "Lima",
  "codigo_postal":"15313",
  "pais": "Perú"
  
}
###
DELETE {{api}}/2