@api=http://localhost:3000


GET {{api}}/articulo/listar
###
POST {{api}}/articulo/crear
Content-Type: application/json

{
  "nombre": "Sofa",
  "tipo_venta":"Peso",
  "precio": 12.50,
  "coste": 60.99,
  "ref": "16573",
  "representacion": "imagen",
  "nombre_categoria": "Abarrotes"
}
###
GET {{api}}/articulo/listar/2
###
PUT {{api}}/articulo/actualizar/2
Content-Type: application/json

{
  "nombre": "Sofa azul",
  "tipo_venta":"Unidad",
  "precio": 12.50,
  "coste": 60.99,
  "ref": "10550",
  "representacion": "imagen",
  "id_categoria": 1
}
###
DELETE {{api}}/articulo/eliminar/7