@api=http://localhost:3000


GET {{api}}/articulo/listar
###
POST {{api}}/articulo/crear
Content-Type: application/json

{
  "nombre": "Cocina",
  "tipo_venta":"Peso",
  "precio": 12.50,
  "coste": 60.99,
  "ref": "10056",
  "representacion": "imagen",
  "categoria": "Sofas"
}
###
GET {{api}}/articulo/listar/4
###
PUT {{api}}/articulo/actualizar/4
Content-Type: application/json

{
  "nombre": "Sofa azul",
  "tipo_venta":"Unidad",
  "precio": 12.50,
  "coste": 60.99,
  "ref": "67777",
  "representacion": "imagen",
  "nombre_categoria": "Botellas"
}
###
DELETE {{api}}/articulo/eliminar/2