@api=http://localhost:3000
###
POST {{api}}/venta
Content-Type: application/json

{
  "detalles": [
    {
      "cantidad": 1,
      "articuloId": 2
    },
    {
        "cantidad": 1,
        "articuloId": 2
    }
  ],
  "tipoPago": "Efectivo",
  "impuestoId": 1,
  "descuentoId": 2,
  "clienteId":1,
  "descuentoId":1,
  "impuestoId":1,
  "usuarioId":1,
  "dineroRecibido":500
}
###
GET {{api}}/reembolso/recibo/56
###
POST {{api}}/reembolsar
Content-Type: application/json

{
  "id": 17, 
  "detalles": [
    {
      "cantidad": 1,
      "articuloId": 2
    },
    {
      "cantidad": 1,
      "articuloId": 1
    }
  ]
}