@api=http://localhost:3000


GET {{api}}/categoria/listar
###
POST {{api}}/categoria/crear
Content-Type: application/json

{
  "nombre": "Libros",
  "color":"Azul"
}
###
GET {{api}}/categoria/listar/6
###
PUT {{api}}/categoria/actualizar/10
Content-Type: application/json

{
  "nombre": "Almohadas",
  "color":"Blanco"
}
###
DELETE {{api}}/categoria/eliminar/6
###
//GET {{api}}/categoria/buscar?search=utensilios