@api=http://localhost:3000/cliente
GET {{api}}
###

###
POST {{api}}
Content-Type: application/json

{
  "nombre": "Estefany Torres",
  "email": "estefanyt3101@gmail.com",
  "telefono": "921448207",
  "direccion": "Calle Las Pasionarias",
  "ciudad": "Lima",
  "region": "Lima",
  "pais": "Perú"
  
}

###
GET {{api}}/2
###
PUT {{api}}/2
Content-Type: application/json

{
  "nombre": "Luis",
  "email": "mino@gmail.com",
  "telefono": "921448207",
  "direccion": "Calle Las Pasionarias",
  "ciudad": "Lima",
  "region": "Lima",
  "codigo_postal":"15313",
  "pais": "Perú"
  
}
###
DELETE {{api}}/2