@api=http://localhost:3000/descuento

POST {{api}}
Content-Type: application/json

{
  "nombre": "Oferta de invierno",
  "tipo_descuento": "%",
  "valor":10
}
###
GET {{api}}/1
###
PUT {{api}}/2
Content-Type: application/json

{
  "nombre": "Oferta de invierno",
  "tipo_descuento": "%",
  "valor":35
}
###
GEt {{api}}

###
DELETE {{api}}/15

###
PUT {{api}}/4/cambiar-estado
Content-Type: application/json

{
  "estado": false
}
