
@api=http://localhost:3000

POST {{api}}/registro
Content-Type: application/json

{
  "nombre": "Unique",
  "email": "estefanyt3101@gmail.com",
  "password": "123345",
  "pais": "Perú"
}
###
POST {{api}}/login
Content-Type: application/json

{
  "email": "estefanyt3101@gmail.com",
  "password": "123345"
}
###
POST {{api}}/eliminar-temporal/8
Content-Type: application/json

{
  "password":"123345",
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJlc3RlZmFueXQzMTAxQGdtYWlsLmNvbSIsImlhdCI6MTcxMTc4MDkwNywiZXhwIjoxNzExODY3MzA3fQ.IZ7vn9nmFwyDIArOpDWM3CWXYcl4VW1kpj0o5Q5L0QA"
}
###
POST {{api}}/restaurar-cuenta/8
###
POST {{api}}/eliminar-cuenta-vencida/7

###
POST {{api}}/eliminar-permanente/8
Content-Type: application/json

{
  "password":"123345",
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJlc3RlZmFueXQzMTAxQGdtYWlsLmNvbSIsImlhdCI6MTcxMTc4MDk1MSwiZXhwIjoxNzExODY3MzUxfQ.M4VfOppiLk668VF1X3MzpK4RTnZ3jKd5oh5WTjWaR6g"
}